"""
Django settings for apps2mweb project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kf@$^y%s+u9u$6gbcv%78dom)9$8%*y#b_e10021e)oyze&ye!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
    
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'applications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'apps2mweb.middleware.CheckCookieMiddleware',
]


#Mialivola no nanisy an'io
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Utilisation de la base de données pour stocker les sessions
SESSION_COOKIE_NAME = 'sessionid'  # Nom du cookie de session
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persiste après la fermeture du navigateur
SESSION_COOKIE_AGE = 86400  # Durée de vie du cookie de session en secondes (ici 1 jour)
SESSION_SAVE_EVERY_REQUEST = True  # Sauvegarder la session à chaque requête

SESSION_COOKIE_SECURE = True  # Assure que le cookie de session est seulement envoyé via HTTPS
SESSION_COOKIE_HTTPONLY = True  # Préviens l'accès aux cookies via JavaScript

# Définir la clé de session pour l'utilisateur connecté
LOGIN_REDIRECT_URL = '/accueil/'  # URL où l'utilisateur est redirigé après la connexion
LOGIN_URL = 'connexion/'  # URL de la page de connexion

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'apps2mweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps2mweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# 'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'apps2m',
#         'USER': 'infor',
#         'PASSWORD': 'servinfodistant',
#         'HOST': '10.169.7.125',  # Remplacez ceci par l'adresse IP de votre base de données
#         'PORT': '3306',
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apps2m',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'sifaka-postgres': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sifaka',
        'USER': 'postgres',
        'PASSWORD': 'tiger',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    },
    'sifaka': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sifaka2',
        'USER': 'postgres',
        'PASSWORD': 'tiger',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.88.28']  # Home
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.137.195']  # Carrefour

import pdfkit

PDFKIT_CONFIG = pdfkit.configuration(wkhtmltopdf='C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe')
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB en octets, ajustez selon vos besoins

# settings.py

# settings.py


# DATABASE_ROUTERS = ['myapp.db_router.DatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'productionfiles'

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'mystaticfiles'
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
